package Tutoria_2;

public class Listado {
    //Colección de objetos...
    Cancion [] listado;

    //Permitir recorrer el listado...
    //Buscar el nombre de una canción, artista, id, ...
    //Comprobar existencia...
    //Eliminar canciones del listado...
    //Agregar canciones al listado...
    //Editar una canción ...
    
}
